clientId: "verifier2"
clientMetadata: {
    client_name: "VP Verifier"
    logo_uri: "https://walt.id/favicon.ico"
    client_uri: "https://walt.id"
}
urlPrefix: "http://localhost:7003/verification-session"
urlHost: "openid4vp://authorize"
